[package]
authors = ["nju33 <nju33.ki@gmail.com>"]
name = "api"
version = "0.1.0"

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = {version = "0.2.8", features = ["handlebars_templates"]}
# }
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"
